### ISSUE TITLE
Add Redmine Issue Link to Description

### ISSUE THREAD

**Issue by ghost** [thegcat/redmine_ical#1]
It would be awesome if the link in the ics description field had a link back to the redmine issue so that when viewing my calendar I can jump quickly.

**Comment by edoceo** [comment]
At or about line #62 of lib/redmine_ical/patch_redmine_classes.rb

```
              description   "#{e[:description]}\n\n#{e[:url]}"
```

**Comment by thegcat** [comment]
Calendar entries already have a URL field and the issue URL is already in there, isn't that enough?

**Comment by edoceo** [comment]
One would think, I sure thought so too. Before I submitted this bug I looked at the ICS output to verify that field is present and works as expected in many Calendaring applications.  However, I'm using this ICS output to my Google Calendar which doesn't use that field.  It's one of the on-going issues with Google Calendar - which, I'll admit, is a sub-par calendaring application - and yes they fully ignore users requests to properly implement iCal.  So, that leaves it to us, with the only option being to embed that URI into the description field.  That URI field is used by Google Calendar or their _URI_ for the event - not the important/authoritative one that we provide.  So; this fix is only required cause Google doesn't play nice.  

I could use another Calendaring application but that Google ones ties so nicely to my phone so I can track my bugs.  Of course that would be easier if Google would respect the feed we're providing - they seem to only check every few hours - and may (or may not) refresh after 24.

**Comment by thegcat** [comment]
Understood, I'll see about it.

**Comment by edoceo** [comment]
Sweet! thank you.

**Comment by thegcat** [comment]
Just added, I don't have an installation to test it anymore though, so I'll leave that to you.
