### ISSUE TITLE
Conflicts w/ https://github.com/cforce/redmine_show_descriptions

### ISSUE THREAD

**Issue by rweng** [thegcat/redmine_ical#4]
When I have both plugins installed in 1.4.4, first an _stack level too deep_-error is shown and then the redmine_ical plugin is disabled. WIthout redmine_show_description, it works fine.

**Comment by thegcat** [comment]
I don't actively use Redmine anymore, so I won't invest the time in trying to fix that myself, sorry. If someone finds a solution, I'll be happy to merge it though.

**Comment by rweng** [comment]
fixed: https://github.com/cforce/redmine_show_descriptions
